ContactUs/urls.py
__author__ = 'chaga'
from django.conf.urls import url
from . import views


urlpatterns = [
   url(r'^$', views.contact, name='contact'),
]

EmailSend/urls.py
__author__ = 'chaga'
from django.conf.urls import url
from . import views


urlpatterns = [
   url(r'^$', views.emailHome, name='emailHome'),
]

EntrepreneurLanding/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^landing', include('HomeSignUp.urls', namespace='HomeSignUp')),
    url(r'^contact/', include('ContactUs.urls', namespace='Contact')),
    url(r'^email/', include('EmailSend.urls', namespace='Email')),
    url(r'^$', include('HomeSignUp.urls', namespace='HomSignUp'))
]

HomeSignUp/urls.py
__author__ = 'chaga'
from django.conf.urls import url
from . import views


urlpatterns = [
   url(r'^$', views.landing, name='landing'),
]

ContactUs/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=240)
    email = models.EmailField()
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.name

EmailSend/models.py
from django.db import models

# Create your models here.

HomeSignUp/models.py
from django.db import models

# Create your models here.
class SignUp(models.Model):
    email = models.EmailField()
    first_name = models.CharField(max_length=120)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    def __str__(self):
        return self.email

ContactUs/forms.py
__author__ = 'chaga'
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'email',
            'name',
            'message'
        ]

EmailSend/forms.py
__author__ = 'chaga'
from django import forms
from HomeSignUp.models import SignUp


class SendEmailForm(forms.Form):
    email_subject = forms.CharField(max_length=80, label='Subject')
    email_body = forms.CharField(widget=forms.Textarea(), label='Body')
    # email_from = forms.EmailField(label='From (your gmail address. Impersonation is looked down upon!)')
    email_to = forms.ModelMultipleChoiceField(
        label='Emails',
        queryset=SignUp.objects.all(),
        required=True
    )

HomeSignUp/forms.py
__author__ = 'chaga'
from django import forms
from .models import SignUp

class SignUpForm(forms.ModelForm):
    class Meta:
        model = SignUp
        fields = [
            'email',
            'first_name'
        ]

ContactUs/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.mail import send_mail
from .forms import ContactForm
# Create your views here.
def contact(request):
    request_post = False
    form = ContactForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        form_email = form.cleaned_data.get('email')
        form_name = form.cleaned_data.get('name')
        form_message = form.cleaned_data.get('message')

        subject = 'Someone Contacted Us!'
        contactMessage = """
        %s at %s: %s
        """%(form_name, form_email, form_message)
        fromEmail = settings.EMAIL_HOST_USER
        toEmail = [fromEmail, 'chagantisidhartha@gmail.com']
        send_mail(subject, contactMessage, fromEmail, toEmail, fail_silently=False)
        instance.save()
    if request.method == 'POST':
        request_post = True
    context = {
        "form":form,
        'submitted':request_post
    }
    return render(request, 'contact.html', context)

EmailSend/views.py
from django.shortcuts import render, redirect
from .forms import SendEmailForm
from django.core.mail import EmailMessage
# Create your views here.
def emailHome(request):

    if request.user.is_authenticated():
        form = SendEmailForm(request.POST or None)

        if form.is_valid():
            email_sub = form.cleaned_data.get('email_subject')
            email_body = form.cleaned_data.get('email_body')
            email_from = ''#form.cleaned_data.get('email_from')
            email_to = list(form.cleaned_data.get('email_to').values_list('email', flat=True))
            email = EmailMessage(
            email_sub,
            email_body,
            email_from,
            email_to,
            ['chagantisidhartha@gmail.com'],
            )
            email.send(fail_silently=False)



        context = {
            'form': form
        }
    else:
        return redirect('HomeSignUp:landing')

    return render(request, 'sendEmail.html', context)

HomeSignUp/views.py
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.conf import settings
from .forms import SignUpForm
import os
# Create your views here.
def landing(request):
    post_request = False
    form = SignUpForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        formName = form.cleaned_data.get('first_name')
        formEmail = form.cleaned_data.get('email')
        fromEmail = settings.EMAIL_HOST_USER
        toEmail = [formEmail]
        subjectMessage = 'Hello %s, here is your PDF!'%(formName)
        sendPDFMessage = """
        Hello, %s,
        Thank you for signing up to our email list. We will make sure to send you worthwhile emails.

        In the mean time, here is your PDF!

        Enjoy,
        %s



        Not you? Don't worry, just ignore this. If you would like to learn of the 10 best businesses to start selling in, though, you can join us at %s.
        """%(formName, fromEmail, settings.CURRENT_URL)
        attachedFile = os.path.join(os.path.join(settings.BASE_DIR, 'attachments'), 'hello.txt')
        email = EmailMessage(
        subjectMessage,
        sendPDFMessage,
        fromEmail,
        toEmail,
        ['chagantisidhartha@gmail.com'],
        )
        email.attach_file(attachedFile)
        email.send(fail_silently=False)
        instance.save()
    if request.method == 'POST':
        post_request = True

    context = {
            'form':form,
            'submitted': post_request
        }
    return render(request, 'home.html', context)

templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Entrepreneur Landing</title>
</head>
<body>
{% include 'nav.html' %}
<div class="container" style="min-height: 800px">
    {%  block content %}

    {% endblock %}
</div>


</body>
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>Contact Us</h1><br/><br/>
    {% if submitted %}
        <div class="row">
            <div class="col-sm-12 text-center">
                <p class="lead">Thank you, your feedback is appreciated</p>
            </div>
        </div>
    {% else %}
    <div class="row">
        <div class="col-sm-4 text-center">
            <p class="lead">Want to let us know of anything? Send us a message here!</p>
        </div>
        <div class="col-sm-8">
            <form action="" method="POST">{% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Send" class="btn btn-primary btn-block"/>
            </form>
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="jumbotron">
    <h2 class="text-center">Get your FREE copy of the 10 best businesses to start selling in!</h2>
    <p class="lead text-center">Enter your email below and your free pdf will be emailed to you!</p>
</div>
<div class="row">
    <div class="col-sm-4">
        <p class="lead text-center">We get it. It's hard to even begin. However, when you join our mailing list, we'll make sure you get the BEST value.</p>
    </div>
    <div class="col-sm-4 pull-right text-center">
        <p class="lead">Along with this pdf, we'll work together to give you the tools to start making money online.</p>
    </div>
</div><br/><br/>
<div class="row">
    <div class="col-sm-12">
        <p class="lead text-center">We promise that we only send you the emails that are worth reading. That means NO SPAM.</p>
    </div>
</div><br/><br/>

{% if submitted %}
    <div class="row">
        <div class="col-sm-12 text-center">
            <p class="lead">Thank you, your email will be sent shortly.</p>
        </div>
    </div>
{% else %}
    <div class="row">
    <div class="col-sm-4 text-center">
        <p class="lead">So what are you waiting for? Sign up now for FREE!</p>
    </div>
    <div class="col-sm-8">
        <form method="POST" action="">{% csrf_token %}
            {{ form|crispy }}
            <input class='btn btn-primary btn-block' type="submit" value="Sign Up Today!"/>
        </form>
    </div>
</div>
{% endif %}

{% endblock %}

templates/nav.html
<nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Entrepreneur Landing</a>
        </div>
        <div id="navbar" class="">
          <ul class="nav navbar-nav">
            <li class=""><a href="{% url 'HomeSignUp:landing' %}">Sign Up</a></li>
            <li><a href="{% url 'Contact:contact' %}">Contact Us</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</nav>

templates/sendEmail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <div class="row">
        <div class="col-sm-6">
            <h1>Send an email</h1>
        </div>
    </div>
    <div class="row">

        <div class="col-sm-6">
            <h4>Send an Email:</h4>

            <form action="" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-block btn-primary" type="submit" value="Send Email to Selected"/>
            </form>
        </div>
        {% if request.POST %}
            <div class="col-sm-6">
                <p class="lead">Email sent!</p>
            </div>
        {% endif %}
    </div>

{% endblock %}